[package]
authors = ["Valentin Tolmer <valentin@tolmer.fr>", "Steve Barrau <steve.barrau@gmail.com>", "Thomas Wickham <mackwic@gmail.com>"]
edition = "2018"
name = "lldap"
version = "0.1.0"

[dependencies]
actix = "0.11.0-beta.3"
actix-http = "3.0.0-beta.6"
actix-rt = "2.1.0"
actix-server = "2.0.0-beta.3"
actix-service = "2.0.0"
actix-web = "4.0.0-beta.3"
anyhow = "*"
rust-argon2 = "0.8"
async-trait = "0.1"
chrono = { version = "*", features = [ "serde" ]}
clap = "3.0.0-beta.2"
cron = "*"
futures = "*"
futures-util = "*"
hmac = "0.10"
http = "*"
jwt = "0.13"
ldap3_server = "*"
lldap_model = { path = "model" }
log = "*"
serde = "*"
serde_json = "1"
sha2 = "0.9"
sqlx-core = "=0.5.1"
thiserror = "*"
time = "0.2"
tokio = { version = "1.2.0", features = ["full"] }
tokio-util = "0.6.3"
tracing = "*"
tracing-actix-web = "0.4.0-beta.7"
tracing-log = "*"
tracing-subscriber = "*"
rand = { version = "0.8", features = ["small_rng", "getrandom"] }

[dependencies.sqlx]
version = "0.5.1"
features = [
  "any",
  "chrono",
  "macros",
  "mysql",
  "postgres",
  "runtime-actix-native-tls",
  "sqlite",
]

[dependencies.sea-query]
version = "0.9.4"
features = ["with-chrono"]

[dependencies.figment]
features = ["env", "toml"]
version = "*"

[dependencies.actix-files]
git = "https://github.com/actix/actix-web"
rev = "2d8530feb37447a1dd2e58700b31b987ae8163ef"

#[dependencies.actix-cors]
#git = "https://github.com/nitnelave/actix-extras"
#rev = "39b03cb5d2734482328722219c528cb0a6d375d7"

[dependencies.actix-web-httpauth]
git = "https://github.com/nitnelave/actix-extras"
rev = "39b03cb5d2734482328722219c528cb0a6d375d7"

[dev-dependencies]
mockall = "0.9.1"
