[package]
authors = ["Valentin Tolmer <valentin@tolmer.fr>"]
edition = "2021"
name = "lldap"
version = "0.4.2-alpha"

[dependencies]
actix = "0.12"
actix-files = "0.6.0-beta.6"
actix-http = "=3.0.0-beta.9"
actix-rt = "2.2.0"
actix-server = "=2.0.0-beta.5"
actix-service = "2.0.0"
actix-web = "=4.0.0-beta.8"
actix-web-httpauth = "0.6.0-beta.2"
anyhow = "*"
async-trait = "0.1"
base64 = "0.13"
bincode = "1.3"
cron = "*"
derive_builder = "0.10.2"
figment_file_provider_adapter = "0.1"
futures = "*"
futures-util = "*"
hmac = "0.10"
http = "*"
itertools = "0.10.1"
juniper = "0.15.10"
juniper_actix = "0.4.0"
jwt = "0.13"
ldap3_proto = { git = "https://github.com/kanidm/ldap3", package = "ldap3_proto" }
log = "*"
orion = "0.16"
rustls = "0.20"
serde = "*"
serde_json = "1"
sha2 = "0.9"
thiserror = "*"
time = "0.2"
tokio-rustls = "0.23"
tokio-stream = "*"
tokio-util = "0.7.3"
tracing = "*"
tracing-actix-web = "0.4.0-beta.7"
tracing-attributes = "^0.1.21"
tracing-log = "*"
rustls-pemfile = "1.0.0"
serde_bytes = "0.11.7"
webpki-roots = "*"

[dependencies.chrono]
features = ["serde"]
version = "*"

[dependencies.clap]
features = ["std", "color", "suggestions", "derive", "env"]
version = "3.1.15"

[dependencies.figment]
features = ["env", "toml"]
version = "*"

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter", "tracing-log"]

[dependencies.lettre]
features = ["builder", "serde", "smtp-transport", "tokio1-rustls-tls"]
default-features = false
version = "0.10.0-rc.3"

[dependencies.lldap_auth]
path = "../auth"

[dependencies.sea-query]
version = "*"
features = ["with-chrono"]

[dependencies.opaque-ke]
version = "0.6"

[dependencies.rand]
features = ["small_rng", "getrandom"]
version = "0.8"

[dependencies.secstr]
features = ["serde"]
version = "*"

[dependencies.tokio]
features = ["full"]
version = "1.17"

[dependencies.uuid]
features = ["v3"]
version = "*"

[dependencies.tracing-forest]
features = ["smallvec", "chrono", "tokio"]
version = "^0.1.4"

[dependencies.actix-tls]
features = ["default", "rustls"]
version = "=3.0.0-beta.5"

[dependencies.image]
features = ["jpeg"]
default-features = false
version = "0.24"

[dependencies.sea-orm]
version= "0.10.3"
default-features = false
features = ["macros", "with-chrono", "with-uuid", "sqlx-all", "runtime-actix-rustls"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls-webpki-roots"]

[dev-dependencies]
mockall = "0.9.1"
